[versions]
kotlin = "2.0.0"
kotlinCoroutines = "1.9.0-RC"
ksp = "2.0.0-1.0.21"

kotlinpoet = "1.17.0"

junit = "5.10.2"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
