[versions]
kotlin = "1.9.0"
kotlinCoroutines = "1.7.2"
ksp = "1.9.0-1.0.11"

kotlinpoet = "1.12.0"

junit = "5.9.2"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
